server:
    port: 8761

# Eureka Server - Configuration
eureka:
    instance:
        appname: ${spring.application.name}
        instanceId: ${spring.application.name}:${random.value}
        hostname: localhost
        lease-renewal-interval-in-seconds: 10
        health-check-url-path: /actuator/health
        secure-health-check-url: /actuator/health
        metadata-map:
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
            startup: ${random.int}    #needed to trigger info and endpoint update after restart
    dashboard:
        enabled: true
        path: /eureka-dashboard
    server:
        waitTimeInMsWhenSyncEmpty: 0
        enable-self-preservation: false
    client:
        fetch-registry: false
        register-with-eureka: false
        service-url:
            default-zone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
        healthcheck:
            enabled: true

# Config Server - Configuration
spring:
    main:
        banner-mode: off
    profiles:
        active: 'dev'
    cloud:
        config:
            server:
                git:
                    clone-on-start: true
                    uri: https://github.com/erithstudio/social-config.git
                prefix: /config
    security:
        user:
            name: admin
            password: admin
    boot:
        admin:
            client:
                url: http://localhost:8761
            routes:
                endpoints:
                    - env
                    - metrics
                    - trace
                    - jolokia
                    - info
                    - configprops
                    - logfile
                    - loggers
                    - refresh
                    - liquibase
                    - heapdump
                    - auditevents
                    - health
                    - httptrace:trace
            url: http://localhost:8761
            username: admin
            password: admin
            ui:
                title: PrimecashX Admin Console
                brand: '<img src="assets/img/icon-spring-boot-admin.svg"><span>PrimecashX Admin Console</span>'
                external-views:
                    - label: "🚀"
                      url: http://localhost:15672/
                      order: 2000
                      iframe: true
                    - label: "🍭"
                      url: http://localhost:8761/eureka-dashboard
                      order: 2001
                      iframe: true

# Logging Configuration
logging:
    file:
        name: "C:/aprisma/logs/service-registry.log"
    pattern:
        file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

## With Spring Actuator, theses data will be visible from '/info'
info:
    name: "@app.artifactId@"
    version: "@app.version@"
    description: "@app.description@"
    running-profile: ${spring.profiles.active}

# management configuration
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: ALWAYS
