server:
    port: 8761

# Eureka Server - Configuration
eureka:
    instance:
        appname: ${spring.application.name}
        instanceId: ${spring.application.name}:${random.value}
        hostname: localhost
        lease-renewal-interval-in-seconds: 10
        health-check-url-path: /actuator/health
        metadata-map:
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
            startup: ${random.int}    #needed to trigger info and endpoint update after restart
    dashboard:
        path: /eureka-dashboard
    server:
        waitTimeInMsWhenSyncEmpty: 0
        enable-self-preservation: false
    client:
        fetch-registry: false
        register-with-eureka: false
        service-url:
            default-zone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
        healthcheck:
            enabled: true

# Config Server - Configuration
spring:
    main:
        banner-mode: off
    profiles:
        active: 'dev'
    cloud:
        config:
            server:
                git:
                    clone-on-start: true
                    uri: https://github.com/erithstudio/social-config.git
                prefix: /config
    security:
        user:
            name: admin
            password: admin

## With Spring Actuator, theses data will be visible from '/info'
info:
    name: "@app.artifactId@"
    version: "@app.version@"
    description: "@app.description@"
    running-profile: ${spring.profiles.active}

# management configuration
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: ALWAYS
