server:
  port: 8080



spring:
  application:
    name: api-gateway
  mvc:
    dispatch-options-request: on
  main:
    banner-mode: off
  cloud:
    loadbalancer:
      ribbon:
        enabled: true

zuul:
  ignoredServices: '*'
  prefix: /api
  ribbon:
    eager-load:
      enabled: true
    eureka:
      enabled: true
  routes:
    multiplications:
      path: /multiplications/**
      serviceId: multiplication
      strip-prefix: false
    results:
      path: /results/**
      serviceId: multiplication
      strip-prefix: false
    leaders:
      path: /leaders/**
      serviceId: gamification
      strip-prefix: false
    stats:
      path: /stats/**
      serviceId: gamification
      strip-prefix: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


#  endpoints:
#    routes:
#      sensitive: false
#    trace:
#      sensitive: false

eureka:
  instance:
    prefer-ip-address: true
    appname: api-gateway
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: false
    registerWithEureka: false
    fetch-registry: true
    fetchRegistry: true
ribbon:
  eureka:
    enabled: true
  eager-load:
    enabled: true

multiplication:
  ribbon:
    listOfServers: localhost:8081
    ServerListRefreshInterval: 15000
gamification:
  ribbon:
    listOfServers: localhost:8082
    ServerListRefreshInterval: 15000