server:
  port: 8080

spring:
  mvc:
    dispatch-options-request: on
  main:
    banner-mode: off

zuul:
  prefix: /api
  routes:
    multiplications:
      path: /multiplications/**
      url: http://localhost:8081/multiplications
    results:
      path: /results/**
      url: http://localhost:8081/results
    leaders:
      path: /leaders/**
      url: http://localhost:8082/leaders
    stats:
      path: /stats/**
      url: http://localhost:8082/stats

  endpoints:
    trace:
      sensitive: true

  ribbon:
    eureka:
      enabled: false